smlua_text_utils_course_acts_replace(COURSE_BOB, "Course 1", ("OVER THE HOTEL"), ("THE PERFECT VIEWPOINT"), ("THE PURPLE SECRET"), ("CANNON ACROSS THE SEA"), ("REDS IN THE SEWERS"), ("FORGOTTEN BUILDING"))
smlua_text_utils_course_acts_replace(COURSE_WF, "Course 2", ("THE WOODEN SLIDE"), ("BETWEEN THE TREES"), ("PATHWAY ALONG THE DIRT"), ("EDGE OF THE FOREST"), ("REDS IN THE POISON WOODS"), ("SURFING OVER THE SPIKES"))
smlua_text_utils_course_acts_replace(COURSE_JRB, "Course 3", ("PATH TO THE LONE HOUSE"), ("ACROSS THE ISLANDS"), ("PILLARS OF THE UNDERWATER CAVE"), ("RAINBOWS TO THE LIGHTHOUSE"), ("THE FORGOTTEN LAGOON"), ("A STAR HAS FALLEN INTO THE RIVER"))
smlua_text_utils_course_acts_replace(COURSE_CCM, "Course 4", ("WALLJUMPS ACROSS THE UPPER RIVER"), ("PANELS OF THE TOWERS"), ("AROUND THE DAM"), ("CAVE OF FLOATING LAVA"), ("INSIDE THE MANY PIPES"), ("OVER THE POISONED POOL"))
smlua_text_utils_course_acts_replace(COURSE_BBH, "Course 5", ("THE LONELY HOUSES"), ("A STRANGELY BUILT TOWN"), ("SCALE THE TOWER"), ("FOG CONSUMED PATHWAYS"), ("REDS OF THE SHINING MOON"), ("ACROSS THE SAND PIPE"))
smlua_text_utils_course_acts_replace(COURSE_HMC, "Course 6", ("WET REDS OF THE CUBE"), ("CAREFULLY OVER THE ROCKS"), ("REDS OF THE COLORFUL SKY"), ("TWISTS AND TURNS OF THE MOUNTAIN"), ("UP AND AROUND IN RETRO SKY"), ("FROZEN OVER PATHWAYS"))
smlua_text_utils_course_acts_replace(COURSE_LLL, "Course 7", ("THE CENTRAL TOWER"), ("THIN ROCK FORMATIONS"), ("PILLARS OF THE POOL"), ("REDS OF THE LAKE"), ("ICY PUZZLE"), ("LAVA TO THE POWER OF 3"))
smlua_text_utils_course_acts_replace(COURSE_SSL, "Course 8", ("FIND THE SECRET ROOM"), ("CANNONS OF THE CRATER"), ("FROM THE BOTTOM TO THE TOP"), ("INSIDE THE VOLCANO"), ("BLOCKY TOWER CLIMB"), ("ABOVE THE CAGE"))
smlua_text_utils_course_acts_replace(COURSE_DDD, "Course 9", ("THE TABLES HAVE TURNED"), ("CRAZY ANGLE JUMPING"), ("OUTLINES OF HOLLOW CUBES"), ("IT'S JUST A NUMBERS GAME"), ("GETTING OVER IT WITH MARIO"), ("OVER ROOFS TO THE TOP"))
smlua_text_utils_course_acts_replace(COURSE_SL, "Course 10", ("PATH OF THE RAINBOW STAIRS"), ("ACROSS THE FLOWER PILLARS"), ("SQUARE WALLJUMPING TO THE SKIES"), ("SECRET BELOW THE GARDEN"), ("THE PURPLE GARDENS"), ("HIDDEN BOXES OF THE BLUE FLAMES"))
smlua_text_utils_course_acts_replace(COURSE_WDW, "Course 11", ("FACE THE BOSS"), ("WHAT A VIEW"), ("PANELS OF THE OIL SLIDE"), ("HIGH OVER THE ROUND BURNERS"), ("THE ENDLESS OIL SEA"), ("SPIRALING STAIRS"))
smlua_text_utils_course_acts_replace(COURSE_TTM, "Course 12", ("SURFING OVER THE SAND"), ("TALE OF THE QUICKSAND FALLS"), ("REDS, SANDS, ROCKS, BUBBLES"), ("FIGHT BETWEEN THE PYRAMIDS"), ("SLIPPERY PYRAMIDS"), ("MASTER OF WALLJUMPING"))
smlua_text_utils_course_acts_replace(COURSE_THI, "Course 13", ("LONGJUMPING OVER THE METROPOLIS"), ("TRUST YOUR INSTINCTS"), ("TOP OF THE HIGHEST SKYSCRAPER"), ("SEWER RED COINS"), ("PARKSIDE STREET REDS"), ("SPEEDING UP WITH WIND"))
smlua_text_utils_course_acts_replace(COURSE_TTC, "Course 14", ("CHUCKYA DANCE PARTY"), ("FORMATIONS IN THE DARK"), ("KEIKI'S TUNNEL OF DOOM"), ("FORMATIONS OF THE LAKE"), ("BUMPING WALLJUMPS"), ("SPADE - BLUE"))
smlua_text_utils_course_acts_replace(COURSE_RR, "Course 15", ("SPADE - PINK"), ("HEART - GREEN"), ("HEART - ORANGE"), ("DIAMOND - PINK"), ("DIAMOND - BLUE"), ("ONE OF THE CASTLE'S SECRET STARS!"))
smlua_text_utils_secret_star_replace(15, "Course 16")
smlua_text_utils_secret_star_replace(16, "Course 17")
smlua_text_utils_secret_star_replace(17, "Course 18")
smlua_text_utils_secret_star_replace(18, "Course 19")
smlua_text_utils_secret_star_replace(19, "Course 20")
smlua_text_utils_secret_star_replace(20, "Course 21")
smlua_text_utils_secret_star_replace(21, "Course 22")
smlua_text_utils_secret_star_replace(22, "Course 23")
smlua_text_utils_secret_star_replace(23, "Course 24")
smlua_text_utils_secret_star_replace(24, "Course 25")
smlua_text_utils_castle_secret_stars_replace("Course 26")
